spring:
  kafka:
    bootstrap-servers: localhost:8001, localhost:8002, localhost:8003
    producer:
      retries: 0
      acks: all
    consumer:
      properties:
        group:
          id: defaultConsumerGroup
      enable-auto-commit: true
      auto-commit-interval: 1000
      auto-offset-reset: latest
    listener:
      missing-topics-fatal: false
