server:
  port: 8087
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/account_a?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456


mybatis:
  type-aliases-package: org.example.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  level:
    root: error
    org.springframework.web: info
    org.apache.ibatis: debug
    io.github.brightloong: debug
  path: "./logs"

